databases:
  - name: servidorAJ
    plan: free
    databaseName: dbrecuperacion
    user: Abraham

services:
  - type: web
    plan: free
    name: Camping
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Camping.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidorAJ
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: camping-dfae.onrender.com





