databases:
  - name: servidor
    plan: free
    databaseName: dbrecuperacion
    user: 

services:
  - type: web
    plan: free
    name: Camping
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Camping.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidor
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: camping-dfae.onrender.com


#DATABASE_URL=postgresql://dbrecuperacion_vfju_user:tGSw9VRX99qjkYkj0onGOmS0h9KYmi4R@dpg-cu084nhu0jms73ct6rg0-a.oregon-postgres.render.com/dbrecuperacion_vfju



